# Generated by Django 4.0 on 2024-02-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_settings_options_settings_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
