# Generated by Django 4.0 on 2024-02-17 20:24

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='user_image/', verbose_name='Cуроту')),
                ('name', models.CharField(max_length=255, verbose_name='Аты жону')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Кыскача маалымат')),
            ],
            options={
                'verbose_name': 'Мугали жонундо кыскача маалымат',
            },
        ),
    ]
