# Generated by Django 4.0 on 2024-02-21 07:05

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_one', models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Мугалим жөнүндө жалпы маалымат ')),
                ('header_two', models.URLField(blank=True, null=True, verbose_name='Мугалимдин ишмердүүлүгү (презентация)')),
                ('header_three', models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Укуктук ченемдик актылар')),
                ('header_four', models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Билим берүү стандарты')),
                ('header_five', models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Өнүктүрүү планы')),
                ('header_six', models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Өнүктүрүү планы')),
                ('header_seven', models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Сабактардын иштелмелери')),
            ],
            options={
                'verbose_name': '1) Документ',
                'verbose_name_plural': '1) Документтер',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='user_image/', verbose_name='Cуроту')),
                ('resume', models.ImageField(upload_to='resume/', verbose_name='Резюме')),
                ('name', models.CharField(max_length=255, verbose_name='Аты жону')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('locations', models.CharField(max_length=255, verbose_name='Адресс')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Кыскача маалымат')),
            ],
            options={
                'verbose_name': '1) Мугали жонундо кыскача маалымат',
            },
        ),
    ]
