# Generated by Django 4.0 on 2024-02-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '1) Мугали жонундо кыскача маалымат'},
        ),
    ]
