# Generated by Django 4.0 on 2024-02-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_seven',
            field=models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Брейринг иштелмелери'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_six',
            field=models.FileField(blank=True, null=True, upload_to='header/', verbose_name='Корсотмо куралдар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(upload_to='resume/', verbose_name='Резюме'),
        ),
    ]
