# Generated by Django 4.0 on 2024-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_one', models.FileField(upload_to='header', verbose_name='Биринчи')),
                ('header_two', models.FileField(upload_to='header', verbose_name='Экинчи')),
                ('header_three', models.FileField(upload_to='header', verbose_name='Учунчу')),
                ('header_four', models.FileField(upload_to='header', verbose_name='Тортунчу')),
                ('header_five', models.FileField(upload_to='header', verbose_name='Бешинчи')),
            ],
            options={
                'verbose_name': '1) Документ',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.ImageField(default=1, upload_to='resume/', verbose_name='Резюме'),
            preserve_default=False,
        ),
    ]
