# Generated by Django 4.0 on 2024-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_header_user_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': '1) Документ', 'verbose_name_plural': '1) Документтер'},
        ),
        migrations.AddField(
            model_name='header',
            name='header_seven',
            field=models.FileField(default=1, upload_to='header', verbose_name='Бешинчи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='header_six',
            field=models.FileField(default=1, upload_to='header', verbose_name='Бешинчи'),
            preserve_default=False,
        ),
    ]
