# Generated by Django 4.0 on 2024-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_header_options_header_header_seven_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.CharField(default=1, max_length=255, verbose_name='Адресс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефонный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='header',
            name='header_five',
            field=models.FileField(upload_to='header/', verbose_name='Өнүктүрүү планы'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_four',
            field=models.FileField(upload_to='header/', verbose_name='Билим берүү стандарты'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_one',
            field=models.FileField(upload_to='header/', verbose_name='Мугалим жөнүндө жалпы маалымат '),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_seven',
            field=models.FileField(upload_to='header/', verbose_name='Сабактардын иштелмелери'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_six',
            field=models.FileField(upload_to='header/', verbose_name='Өнүктүрүү планы'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_three',
            field=models.FileField(upload_to='header/', verbose_name='Укуктук ченемдик актылар'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_two',
            field=models.FileField(upload_to='header/', verbose_name='Мугалимдин ишмердүүлүгү (презентация)'),
        ),
    ]
