# Generated by Django 4.0 on 2024-02-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_email_user_locations_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_two',
            field=models.URLField(verbose_name='Мугалимдин ишмердүүлүгү (презентация)'),
        ),
    ]
