# Generated by Django 5.0.1 on 2024-01-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': '1) Пользователь телеграм', 'verbose_name_plural': '1) Пользователи телеграма'},
        ),
    ]
